Remove trusty-irq.ko files due to not in use.
ERROR: trusty-irq.ko has a version of 10024584, expecting 10029123.

Bug: 280013450
Signed-off-by: irischen <irischen@google.com>
(cherry picked from https://googleplex-android-review.googlesource.com/q/commit:9af1fbc09fbce69ab6eafd88ad3b72ffb88ab78d)
Merged-In: I5a8ed7813a0b02a7fbcb180dd02339537872e553
Change-Id: I5a8ed7813a0b02a7fbcb180dd02339537872e553